### ISSUE TITLE
Cache prisma engines in CI

### ISSUE THREAD

**Issue by RobertCraigie** [RobertCraigie/prisma-client-py#550]
We currently do not do any form of caching on the Prisma engine binaries, this would greatly improve CI times.

**Comment by Leon0824** [comment]
You could make a cache in your CI pipeline configuration.

Here is an example for Drone CI.

pyproject.toml:

```toml
[tool.prisma]
# cache engine binaries in a directory relative to your project
binary_cache_dir = './prisma/binaries/' # Full path in CI runner: /drone/src/prisma/binaries/
```

.drone.yml
```yaml
kind: pipeline
type: docker
name: default

volumes:
  - name: prisma
    host:
      path: /tmp/drone/cache/prisma/ # Cached files keep in CI runner host

steps:
  - name: test
    image: node:18-bullseye
    volumes:
      - name: prisma
        path: /drone/src/prisma/binaries/
    commands:
      - prisma migrate dev
```
