### ISSUE TITLE
Can't run prisma migrate on mysql8:  Unknown authentication plugin `sha256_password'.

### ISSUE THREAD

**Issue by travisneilturner** [RobertCraigie/prisma-client-py#744]
## Bug description

Using this docker-compose: 
```yaml
version: "3.9"

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
```

When I run 
```bash
❯ prisma migrate dev --name init
```

I see: 
```
Environment variables loaded from .env
Prisma schema loaded from schema.prisma
Datasource "db": MySQL database "mydatabase" at "localhost:3306"

Error: Migration engine error:
Error querying the database: Unknown authentication plugin `sha256_password'.
```

## How to reproduce

Run ```bash
prisma migrate dev --name init
```

## Expected behavior

The migrations are applied successfully

## Prisma information

<!-- Your Prisma schema, Prisma Client Python queries, ...
Do not include your database credentials when sharing your Prisma schema! -->

```prisma
datasource db {
  provider = "mysql"
  url      = env("DATABASE_URL")
}

// generator
generator client {
  provider             = "prisma-client-py"
  interface            = "asyncio"
  recursive_type_depth = 5
}

model Organization {
  id   String @id @default(cuid())
  name String

  websiteUrl   String?
  contactEmail String?

  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  users User[]
}

```

## Environment & setup

- OS:  MacOS Ventura
- Database: MySQL 8
- Python version: Python 3.10.10
- Prisma version:

```
prisma                  : 4.11.0
prisma client python    : 0.8.2
platform                : darwin
expected engine version : 8fde8fef4033376662cad983758335009d522acb
installed extras        : []
install path            : /Users/highlander85/Library/Caches/pypoetry/virtualenvs/my-service-hE8eyDXL-py3.10/lib/python3.10/site-packages/prisma
binary cache dir        : /Users/highlander85/.cache/prisma-python/binaries/4.11.0/8fde8fef4033376662cad983758335009d522acb
```
